### ISSUE TITLE
Add GISAID isolate ID to acknowledgments download

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/seasonal-flu#178]
Flagged [internally](https://support.nextstrain.org/agent/nextstrain/nextstrain/tickets/details/668036000007764001) by @rneher that the acknowledgements download does not include the GISAID isolate IDs. 

https://github.com/nextstrain/seasonal-flu/pull/138 added the HA/NA _segment_ accessions, but we do not include the isolate ID used to link multiple segments to the same isolate. The isolate id was added to the metadata upload in https://github.com/nextstrain/seasonal-flu/pull/160, so it should be available in the metadata for the builds. 

The fields included in the acknowledgements is [hardcoded in Auspice](https://github.com/nextstrain/auspice/blob/dae78e74d5e06303d901387adf9fe7550a7d4aa9/src/components/download/helperFunctions.js#L326) so the field will have to be named `gisaid_epi_isl`. 

## TODOs
- [x] https://github.com/nextstrain/seasonal-flu/pull/179
- [x] Re-run upload workflow to update S3 column names
- [x] https://github.com/nextstrain/seasonal-flu/pull/180

**Comment by joverlee521** [comment]
@huddlej, would it break any of your workflows to rename the [fasta_fields](https://github.com/nextstrain/seasonal-flu/blob/1677cc2e1a5b824824d2aeb770fe3939dab0d694/profiles/upload.yaml#L28) to `gisaid_epi_isl`?

**Comment by joverlee521** [comment]
Ah, at least the [nextclade workflow](https://github.com/nextstrain/seasonal-flu/blob/1677cc2e1a5b824824d2aeb770fe3939dab0d694/nextclade/Snakefile#L414) is using the `isolate_id` field. 

Maybe better to just rename `isolate_id` to `gisaid_epi_isl` within the phylogenetic workflow right before the `augur export`?

**Comment by huddlej** [comment]
I don't depend on `isolate_id` as a field name anywhere. Since Auspice hardcodes separate fields for GISAID and GenBank accessions (without an awareness of segmented viruses), it makes sense to rename `isolate_id` to `gisaid_epi_isl` in the uploaded metadata.

Unless the Nextclade somehow depends on an `isolate_id` field downstream, I would just change the Nextclade workflow to use the new field name, too.

**Comment by joverlee521** [comment]
Reopening because we've removed `gisaid_epi_isl` from metadata in https://github.com/nextstrain/seasonal-flu/pull/188. 

This issue now depends on https://github.com/nextstrain/fauna/issues/165

**Comment by huddlej** [comment]
Thanks to hard work by @joverlee521, this issue no longer depends on https://github.com/nextstrain/fauna/issues/165 and instead depends on https://github.com/nextstrain/seasonal-flu/issues/234. Once that seasonal flu repo issue is closed, we can revert the commits from https://github.com/nextstrain/seasonal-flu/pull/188 to return the GISAID EPI ISLs back to the acknowledgments.
